//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapaBobMegaChallenge.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public System.Guid order_id { get; set; }
        public Size size { get; set; }
        public Crust crust { get; set; }
        public bool sausage { get; set; }
        public decimal cost { get; set; }
        public PaymentType payment_type { get; set; }
        public System.Guid customer_id { get; set; }
        public bool pepperoni { get; set; }
        public bool onions { get; set; }
        public bool green_peppers { get; set; }
        public bool completed { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
